name: lint/formatter
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install black
        run: pip install black
      - name: Run black
        run: black --check --verbose .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: actions/checkout@v6
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort --check-only --settings-file=pyproject.toml libthumbor tests
